### ISSUE TITLE
Redis mutex does not require digest

### ISSUE THREAD

**Issue by graywolf-at-work** [kenn/redis-mutex#31]
```
Traceback (most recent call last):
        2: from ./bm.rb:6:in `<main>'
        1: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- redis_mutex (LoadError)
        6: from ./bm.rb:6:in `<main>'
        5: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
        4: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `rescue in require'
        3: from /usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:130:in `require'
        2: from /home/dockwolf/.gem/ruby/2.6.0/gems/redis_mutex-0.0.2/lib/redis_mutex.rb:4:in `<top (required)>'
        1: from /home/dockwolf/.gem/ruby/2.6.0/gems/redis_mutex-0.0.2/lib/redis_mutex.rb:32:in `<class:RedisMutex>'
/home/dockwolf/.gem/ruby/2.6.0/gems/redis_mutex-0.0.2/lib/redis_mutex.rb:11:in `def_redis_script': uninitialized constant RedisMutex::Digest (NameError)
```

bug repro:

```
require "redis_mutex"
```

Workaround:

```
require "digest"
require "redis_mutex"
```

Expected outcome: If redis mutex is using digest module, it should probably require it. It's possible this is new issue under ruby 2.6.0.

**Comment by graywolf-at-work** [comment]
Out of curiosity, why was this closed? It still seems to be an issue.

**Comment by kenn** [comment]
You are using `redis_mutex-0.0.2`which is a different gem I guess?
